Repository OmegaBox/React_Frontend, pull requests merged in 2020-07, with the labels that each got.

#55 feat: make BoxOffice component
  src/Components/Organisms/Footer.js
  src/Components/Organisms/Header.js
  src/Components/Organisms/Main/MainBenefits.js
  src/Components/Organisms/Main/MainBenefits.scss
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/MainBoxOffice.scss
  src/Components/Organisms/Main/MainCuration.js
  src/Components/Organisms/Main/MainLink.js
  src/Components/Organisms/Main/MainNotice.js
  src/Components/Organisms/Main/MainTheater.js
  src/Components/Organisms/Main/style/MainBenefits.scss
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/Main/style/MainCuration.scss
  src/Components/Organisms/Main/style/MainLink.scss
  src/Components/Organisms/Main/style/MainNotice.scss
  src/Components/Organisms/Main/style/MainTheater.scss
  src/Components/Organisms/style/Footer.scss
  src/Components/Organisms/style/Header.scss
  src/common.scss
  src/images/omegaGray.png
Labels: feature

#57 fix: fix scss bug
  src/Components/Molecules/CarouselCalendar.js
  src/Components/Molecules/CarouselTimeline.js
  src/Components/Molecules/style/BookingMovieList.scss
  src/Components/Molecules/style/BookingMovieSchedules.scss
  src/Components/Molecules/style/BookingSelectTime.scss
  src/Components/Molecules/style/BookingTheaterList.scss
  src/Components/Molecules/style/Calendar.scss
  src/Components/Molecules/style/CarouselCalendar.scss
  src/Components/Molecules/style/CarouselTimeline.scss
  src/Components/Organisms/Booking/style/BookingSelectMovie.scss
  src/Components/Organisms/style/Footer.scss
  src/Components/Organisms/style/Header.scss
  src/Components/Pages/mypage.scss
  src/Components/Pages/mypageSample.scss
  src/Reducer/bookingReducer.js
  src/common.scss
  src/commonVariable.scss
  src/index.js
Labels: bug

#58 fix: fix scss import bug
  src/Components/Organisms/Main/style/MainBenefits.scss
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/Main/style/MainCuration.scss
  src/Components/Organisms/Main/style/MainLink.scss
  src/Components/Organisms/Main/style/MainNotice.scss
  src/Components/Organisms/Main/style/MainTheater.scss
  src/Components/Organisms/style/Footer.scss
  src/Components/Organisms/style/Header.scss
Labels: bug

#61 feat: movieDetailPage init
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/NavSample.js
  src/Components/Pages/MovieDetailPage.js
  src/Components/Templates/MovieDetail.js
  src/Router/MainRouter.js
Labels: feature

#62 Feat: Made Component about select seat and popup
  public/index.html
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingPersonalCounter.js
  src/Components/Molecules/BookingPersonalSetting.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/BookingSeatReset.js
  src/Components/Molecules/PopupNotice.js
  src/Components/Molecules/style/BookingInfo.scss
  src/Components/Molecules/style/BookingPersonalSetting.scss
  src/Components/Molecules/style/BookingSeatList.scss
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Components/Organisms/Booking/style/BookingSelectSeat.scss
  src/Reducer/bookingReducer.js
  src/Reducer/bookingSeatReducer.js
  src/Reducer/index.js
  src/Reducer/utilModalReducer.js
  src/common.scss
Labels: feature

#63 mypage dashboard persnalInfo
  package-lock.json
  src/Components/Molecules/PopupChoiceTheater.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Components/Pages/mypage.scss
  src/Reducer/userInfoReducer.js
  src/common.scss
Labels: feature

#66 Docs: Changed file name
  src/Components/Molecules/BookingPersonalCounter.js
  src/Components/Molecules/BookingSeatReset.js
  src/Components/Molecules/PopupNotice.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Components/Organisms/Booking/style/BookingSelectSeat.scss
  src/Reducer/bookingReducer.js
  src/Reducer/index.js
  src/Reducer/modalReducer.js
Labels: feature

#68 Feat: Made logic about Social Distance and handicapped Seat
  src/Components/Molecules/BookingPersonalCounter.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/style/BookingPersonalSetting.scss
  src/Components/Molecules/style/BookingSeatList.scss
  src/Components/Organisms/Booking/style/BookingSelectSeat.scss
  src/commonVariable.scss
Labels: feature

#69 feat : mypage dash board bookingList, popup
  src/Components/Molecules/BookingCancel.js
  src/Components/Molecules/BookingSeatReset.js
  src/Components/Molecules/PopupNotice.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Reducer/modalReducer.js
  src/Reducer/userInfoReducer.js
  src/common.scss
Labels: feature

#71 Docs: Modified modal popup reducer
  src/Components/Molecules/BookingPersonalCounter.js
  src/Components/Molecules/BookingSeatReset.js
  src/Reducer/modalReducer.js
Labels: feature

#72 feat : eat: dashBoard movieStory outfut
  src/Components/Molecules/BookingCancel.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
Labels: feature

#75 feat: Make api & action
  package.json
  src/Api/api.js
  src/Components/Molecules/BookingMovieList.js
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Molecules/Calendar.js
  src/Components/Molecules/CarouselTimeline.js
  src/Components/Molecules/style/BookingTheaterList.scss
  src/Components/Organisms/Booking/BookingSelectMovie.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Reducer/bookingReducer.js
  src/Reducer/index.js
  src/index.js
  yarn.lock
Labels: feature

#76 feat: make boxOffice Reducer
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Reducer/index.js
  src/Reducer/initMovieReducer.js
  src/Reducer/movieReducer.js
Labels: feature

#78 feat: Make reducer & actions
  src/Components/Molecules/BookingMovieList.js
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Molecules/style/BookingMovieList.scss
  src/Components/Molecules/style/BookingTheaterList.scss
  src/Reducer/bookingReducer.js
Labels: feature

#80 feat: Make fast booking title
  src/Components/Atoms/BookingFastTitle.js
  src/Components/Atoms/style/BookingFastTitle.scss
  src/Components/Organisms/Booking/BookingSelectMovie.js
Labels: feature

#82 Feat: Finished BookingSeatInfo component feats
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/style/BookingInfo.scss
  src/Components/Molecules/style/BookingSeatList.scss
  src/Reducer/bookingSeatReducer.js
  src/Utils/ultil.js
Labels: feature

#86 feat: make movieDetail page layout init, main animation
  src/Api/api.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/Main/style/MainNotice.scss
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/MovieDetail/style/MovieDetailWrap.scss
  src/Components/Organisms/MovieDetail/style/MovieInforWrap.scss
  src/Components/Templates/MovieDetail.js
  src/Reducer/movieReducer.js
Labels: feature

#87 feat: Make search schedule api & reducer
  src/Api/api.js
  src/Components/Atoms/BookingFastTitle.js
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Molecules/CarouselCalendar.js
  src/Components/Molecules/style/CarouselCalendar.scss
  src/Components/Molecules/style/CarouselTimeline.scss
  src/Reducer/bookingReducer.js
  src/Utils/ultil.js
  src/index.js
Labels: feature

#89 Docs: Made Login and signup component
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/SignUpForm.js
  src/Components/Organisms/style/LoginForm.scss
  src/Components/Organisms/style/SignUpForm.scss
  src/Components/Pages/LoginAndSignUpPage.js
  src/Components/Templates/LoginAndSignUp.js
  src/Router/MainRouter.js
  src/Router/SubLoginSignUpRouter.js
  src/common.scss
Labels: feature

#90 fix: fix movieReducer & boxofficeComponent
  src/Components/Molecules/BookingMovieList.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Reducer/movieReducer.js
Labels: feature

#93 fix: fix layout & add map
  package.json
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Molecules/Calendar.js
  src/Components/Molecules/CarouselCalendar.js
  src/Components/Molecules/TeatherMap.js
  src/Components/Molecules/style/BookingTheaterList.scss
  src/Components/Molecules/style/CarouselCalendar.scss
  src/Components/Molecules/style/TheaterMap.scss
  src/Components/Organisms/Booking/BookingSelectTimeAndTheater.js
  src/Reducer/bookingReducer.js
  src/Router/SubBookingRouter.js
  src/Utils/theaterLoaction.js
  yarn.lock
Labels: feature, fix

#94 feat : movieDetail layout
  package-lock.json
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/MovieDetail/style/MovieDetailWrap.scss
  src/Components/Organisms/MovieDetail/style/MovieInforWrap.scss
  src/common.scss
Labels: feature

#97 fix: main boxOffice animation
  src/Components/Molecules/MainHeader.js
  src/Components/Molecules/Search.js
  src/Components/Molecules/SubHeader.js
  src/Components/Organisms/Header.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/MainCuration.js
  src/Components/Organisms/Main/MainLink.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/Main/style/MainCuration.scss
  src/Components/Organisms/Main/style/MainLink.scss
  src/Components/Organisms/NavSample.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Components/Pages/WholeMovieListPage.js
  src/Components/Templates/WholeMovieList.js
  src/Reducer/index.js
  src/Reducer/initMovieReducer.js
  src/Router/MainRouter.js
  src/common.scss
Labels: feature

#101 fix: fix proxy & add: api, reducer
  package.json
  src/Api/api.js
  src/Components/Molecules/BookingMovieList.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/BookingSelectTime.js
  src/Components/Molecules/Calendar.js
  src/Components/Molecules/CarouselCalendar.js
  src/Components/Molecules/style/BookingMovieList.scss
  src/Reducer/bookingReducer.js
  src/setupProxy.js
  yarn.lock
Labels: feature, fix

#102 fix: make whole movie list page
  src/Components/Molecules/Search.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Components/Organisms/style/Header.scss
  src/Reducer/movieReducer.js
Labels: fix

#105 Feat: Connected Seat API and Made sign up component func
  src/Components/Molecules/BookingNotice.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/style/BookingNotice.scss
  src/Components/Molecules/style/BookingSeatList.scss
  src/Components/Organisms/Booking/BookingTicket.js
  src/Components/Organisms/Booking/style/BookingTicket.scss
  src/Components/Organisms/SignUpForm.js
  src/Components/Organisms/style/SignUpForm.scss
  src/Utils/ultil.js
  src/common.scss
  src/images/google_logo.png
Labels: feature

#106 feat: Make api connections
  src/Api/api.js
  src/Components/Molecules/BookingMovieList.js
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Molecules/CarouselCalendar.js
  src/Components/Molecules/CarouselTimeline.js
  src/Reducer/bookingReducer.js
Labels: feature

#109 feat: myMovieStroy
  src/Components/Molecules/MyMovieStoryComment.js
  src/Components/Molecules/MyMovieStoryFavorite.js
  src/Components/Molecules/MyMovieStoryTimeLine.js
  src/Components/Molecules/MyMovieStoryWatched.js
  src/Components/Organisms/MyPage/MyMovieStory.js
  src/Components/Pages/mypage.scss
  src/Reducer/userInfoReducer.js
  src/Reducer/userInfoReducerNewSample.js
  src/common.scss
Labels: feature

#112 Docs: Added alt attr in img tag
  src/Components/Molecules/BookingInfo.js
Labels: fix

#113 feat: payment Layout
  package-lock.json
  src/Components/Molecules/Search.js
  src/Components/Organisms/Booking/BookingPayment.js
  src/Components/Organisms/Booking/style/BookingPayment.scss
  src/Components/Pages/mypage.scss
  src/common.scss
  src/commonVariable.scss
Labels: feature

#116 feat: Make time select button & function
  src/Api/api.js
  src/Components/Atoms/Loading.js
  src/Components/Atoms/style/Loading.scss
  src/Components/Molecules/BookingMovieList.js
  src/Components/Molecules/BookingSelectTime.js
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Molecules/CarouselCalendar.js
  src/Components/Molecules/CarouselTimeline.js
  src/Components/Molecules/style/BookingMovieList.scss
  src/Components/Molecules/style/BookingSelectTime.scss
  src/Components/Molecules/style/BookingTheaterList.scss
  src/Reducer/bookingReducer.js
  src/Utils/theaterLocation.js
Labels: feature

#117 Feat: Failed connected api
  src/Api/api.js
  src/Components/Organisms/SignUpForm.js
  src/Components/Organisms/style/SignUpForm.scss
  src/Utils/ultil.js
  src/setupProxy.js
Labels: feature

#118 feat: movie detail page router
  src/Components/Organisms/Header.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/MainLink.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/Main/style/MainCuration.scss
  src/Components/Organisms/Main/style/MainLink.scss
  src/Components/Organisms/Main/style/MainNotice.scss
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/NavSample.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Components/Organisms/style/Header.scss
  src/Components/Pages/MainPage.js
  src/Components/Pages/MovieDetailPage.js
  src/Components/Pages/WholeMovieListPage.js
  src/Reducer/movieReducer.js
  src/Router/MainRouter.js
Labels: feature

#120 feat : paymentTicket layout
  src/App.js
  src/Components/Molecules/style/BookingNotice.scss
  src/Components/Organisms/Booking/BookingTicket.js
  src/Components/Organisms/Booking/style/BookingTicket.scss
  src/Components/Organisms/NavSample.js
  src/common.scss
Labels: feature

#121 fix: fix proxy
  src/Api/api.js
  src/Components/Organisms/SignUpForm.js
  src/Router/MainRouter.js
  src/setupProxy.js
Labels: feature

#125 Feat: Connected API in signup page
  src/Api/api.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Organisms/SignUpForm.js
Labels: feature

#126 fix: detail Page Router
  src/Api/api.js
  src/Components/Molecules/MainHeader.js
  src/Components/Molecules/SubHeader.js
  src/Components/Organisms/Header.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/MainNotice.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/NavSample.js
  src/Components/Organisms/SubHeader.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Components/Organisms/style/Header.scss
  src/Components/Organisms/style/MainHeader.scss
  src/Components/Organisms/style/SubHeader.scss
  src/Components/Pages/MovieDetailPage.js
  src/Reducer/movieReducer.js
  src/Router/MainRouter.js
Labels: feature

#127 fix: header code
  src/Components/Organisms/Header.js
  src/Components/Organisms/style/Header.scss
Labels: feature

#129 feat : eventPage Layout
  src/Components/Organisms/Event/DiscountEvent.js
  src/Components/Organisms/Event/MegaPick.js
  src/Components/Organisms/Event/MovieEvent.js
  src/Components/Organisms/Event/PremiereEvent.js
  src/Components/Organisms/Event/RecommendEvent.js
  src/Components/Organisms/Event/TheaterEvent.js
  src/Components/Organisms/Event/style/EventCommon.scss
  src/Components/Organisms/NavSample.js
  src/Components/Pages/EventPage.js
  src/Components/Templates/Event.js
  src/Router/MainRouter.js
Labels: feature

#130 feat: main visual, header disign style
  src/Components/Organisms/Header.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/style/MainHeader.scss
Labels: feature

#131 Feat: Connected Api in Booking Seat component
  src/Components/Atoms/style/BookingFastTitle.scss
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/style/BookingInfo.scss
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Components/Organisms/Booking/style/BookingSelectSeat.scss
Labels: feature

#132 merge: merging
  package.json
  src/Api/api.js
  src/Components/Molecules/style/BookingSelectTime.scss
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Reducer/bookingReducer.js
  src/Reducer/index.js
  src/Reducer/userInfoReducer.js
  src/Router/MainRouter.js
  src/setupProxy.js
  yarn.lock
Labels: feature

#133 style: style modify
  package-lock.json
  src/Components/Organisms/Booking/BookingPayment.js
  src/Components/Organisms/Booking/style/BookingPayment.scss
  src/Components/Organisms/Booking/style/BookingTicket.scss
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/style/MovieDetailWrap.scss
  src/Components/Organisms/MovieDetail/style/MovieInforWrap.scss
Labels: style

#134 fix: detail page
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Pages/BookingPage.js
  src/Components/Pages/MainPage.js
  src/Components/Pages/MovieDetailPage.js
  src/Components/Pages/WholeMovieListPage.js
  src/Reducer/movieReducer.js
Labels: fix

#138 Fix: Can't solved issue
  src/Api/api.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Reducer/bookingSeatReducer.js
  src/Utils/ultil.js
Labels: fix

#140 feat: subPage header Design, page util
  src/Components/Organisms/Header.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/SubHeader.js
  src/Components/Organisms/style/MainHeader.scss
Labels: feature

#141 feat : event Page layout
  src/Components/Organisms/Event/DiscountEvent.js
  src/Components/Organisms/Event/MegaPick.js
  src/Components/Organisms/Event/MovieEvent.js
  src/Components/Organisms/Event/PremiereEvent.js
  src/Components/Organisms/Event/RecommendEvent.js
  src/Components/Organisms/Event/TheaterEvent.js
  src/Components/Organisms/Event/style/EventCommon.scss
  src/Components/Organisms/MainHeader.js
Labels: feature

#143 Feat: Connected Api of totalPrice in SelectSeat component
  src/Api/api.js
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Reducer/bookingSeatReducer.js
Labels: feature

#146 feat: make login funcs
  src/Api/api.js
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/NavSample.js
  src/Components/Pages/MainPage.js
  src/Reducer/userInfoReducer.js
  src/Router/MainRouter.js
Labels: feature

#148 fix: refresh bug fix
  src/Api/api.js
  src/Components/Pages/BookingPage.js
  src/Reducer/userInfoReducer.js
Labels: fix

#149 fix: header code
  src/Api/api.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/style/MainHeader.scss
  src/Components/Pages/MovieDetailPage.js
  src/Reducer/movieReducer.js
  src/Router/MainRouter.js
  src/setupProxy.js
Labels: fix

#151 fix: fix proxy bug
  src/Api/api.js
  src/Components/Pages/MovieDetailPage.js
  src/Reducer/bookingReducer.js
  src/setupProxy.js
Labels: fix

#153 fix: fix gps error
  src/Utils/theaterLocation.js
Labels: fix

#154 Feat: Made popup in sign up page
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/PopupNotice.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Components/Organisms/SignUpForm.js
  src/Reducer/modalReducer.js
  src/Router/SubLoginSignUpRouter.js
Labels: feature

#158 fix: detail page information
  src/Api/api.js
  src/Components/Molecules/LogOut.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/MovieDetail/style/MovieDetailWrap.scss
  src/Components/Organisms/MovieDetail/style/MovieInforWrap.scss
  src/Components/Organisms/SubHeader.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Components/Organisms/style/MainHeader.scss
  src/Components/Organisms/style/SubHeader.scss
  src/Components/Pages/MovieDetailPage.js
  src/Reducer/movieReducer.js
  src/setupProxy.js
Labels: fix

#157 Fix: Modified reserved Seat Api call func
  src/Components/Molecules/BookingSeatList.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
Labels: feature

#160 feat: Check login popups
  src/Api/api.js
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/style/LoginForm.scss
  src/Components/Pages/BookingPage.js
  src/Reducer/userInfoReducer.js
  src/Utils/ultil.js
  src/common.scss
Labels: feature

#162 fix: fix cookie bug & some reducer
  src/Components/Organisms/LoginForm.js
  src/Reducer/userInfoReducer.js
  src/Utils/ultil.js
Labels: fix

#164 fix: movie datail page
  src/Components/Molecules/LogOut.js
  src/Components/Organisms/Main/MainCuration.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/MovieDetail/style/MovieInforWrap.scss
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Pages/MovieDetailPage.js
  src/Reducer/movieReducer.js
Labels: fix

#168 Feat: Made feature connecting reservetion Api and Stored seat states in ticket state
  src/Api/api.js
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/PopupNotice.js
  src/Components/Molecules/style/BookingInfo.scss
  src/Components/Molecules/style/BookingSeatList.scss
  src/Components/Organisms/Booking/BookingPayment.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/setupProxy.js
Labels: feature

#169 feat: Make disable titles
  src/Api/api.js
  src/Components/Molecules/BookingMovieList.js
  src/Components/Molecules/style/BookingMovieList.scss
  src/Components/Organisms/LoginForm.js
  src/Components/Pages/BookingPage.js
  src/Reducer/bookingReducer.js
  src/setupProxy.js
Labels: feature

#172 fix & refactor: refactoring states refactor, fix no reservation info bug fix
  src/Api/api.js
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingMovieList.js
  src/Reducer/bookingReducer.js
Labels: feature, fix

#174 feat: Make loading effect
  package.json
  src/Components/Atoms/EmptySchedules.js
  src/Components/Atoms/SkeletonRegion.js
  src/Components/Atoms/SkeletonTheater.js
  src/Components/Atoms/SkeletonTimeSelect.js
  src/Components/Atoms/style/EmptySchedules.scss
  src/Components/Molecules/BookingSelectTime.js
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Molecules/CarouselCalendar.js
  src/Components/Molecules/style/BookingMovieList.scss
  src/Components/Molecules/style/CarouselCalendar.scss
  src/Reducer/bookingReducer.js
  src/images/movieTime.png
  yarn.lock
Labels: feature, style

#179 Docs: Rebuild reducer Making Reservation api
  src/Components/Molecules/BookingInfo.js
  src/Reducer/bookingReducer.js
Labels: docs

#180 feat: Make default payment page, fix: fix some initail state
  .gitignore
  package.json
  src/Api/api.js
  src/Components/Molecules/BookingMovieList.js
  src/Components/Organisms/Booking/BookingPayment.js
  src/Reducer/bookingReducer.js
  src/Utils/payment.js
  yarn.lock
Labels: feature, fix

#181 Feat: Made feat Holding Seat and Added and Connected priceList state
  src/Api/api.js
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Components/Organisms/SignUpForm.js
  src/Reducer/bookingReducer.js
  src/Reducer/bookingSeatReducer.js
  src/Reducer/index.js
Labels: feature

#183 feat: mypage api
  package-lock.json
  src/Api/api.js
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/ConfirmPassword.js
  src/Components/Organisms/MyPage/EditOption.js
  src/Components/Organisms/MyPage/EditUserInfo.js
  src/Components/Organisms/MyPage/MyMovieStory.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Components/Organisms/MyPage/Snb.js
  src/Components/Organisms/MyPage/style/BookingHistoryWrap.scss
  src/Components/Organisms/MyPage/style/ConfirmPassword.scss
  src/Components/Organisms/MyPage/style/EditOption.scss
  src/Components/Organisms/MyPage/style/EditPassword.scss
  src/Components/Organisms/MyPage/style/EditUserInfo.scss
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
  src/Components/Organisms/MyPage/style/MypageDashBoard.scss
  src/Components/Organisms/MyPage/style/Snb.scss
  src/Components/Organisms/SignUpForm.js
  src/Components/Organisms/style/LoginForm.scss
  src/Components/Organisms/style/SignUpForm.scss
  src/Components/Pages/MyPage.js
  src/Components/Pages/WholeMovieListPage.js
  src/Components/Pages/mypage.scss
  src/Components/Pages/style/mypage.scss
  src/Components/Templates/MyMegaBox.js
  src/Reducer/userInfoReducer.js
  src/common.scss
  src/key.json
Labels: feature

#184 feat: Make billing server auth & ticket page
  src/Api/api.js
  src/Components/Atoms/SkeletonRegion.js
  src/Components/Atoms/SkeletonTheater.js
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/Calendar.js
  src/Components/Molecules/CarouselCalendar.js
  src/Components/Organisms/Booking/BookingPayment.js
  src/Components/Organisms/Booking/BookingTicket.js
  src/Components/Organisms/Booking/style/BookingPayment.scss
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Components/Organisms/SignUpForm.js
  src/Reducer/bookingReducer.js
  src/Reducer/userInfoReducer.js
  src/Utils/util.js
Labels: feature

#185 fix: fix mypage detail api
  src/Api/api.js
  src/Reducer/userInfoReducer.js
Labels: fix

#190 feat: make detail page chart
  package-lock.json
  package.json
  src/Api/api.js
  src/Components/Molecules/ChartBookingRating.js
  src/Components/Molecules/LineDayAudience.js
  src/Components/Molecules/RaderChartKeyPoint.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/MovieDetail/style/MovieInforWrap.scss
  src/Components/Pages/MovieDetailPage.js
  src/Reducer/movieReducer.js
  yarn.lock
Labels: feature

#189 Fix: Modified PriceList state and PriceProcess text
  src/Components/Molecules/BookingInfo.js
  src/Components/Organisms/Booking/BookingPayment.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Reducer/bookingReducer.js
Labels: fix

#192 fix: logout event
  src/Components/Molecules/ChartBookingRating.js
  src/Components/Molecules/RaderChartKeyPoint.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Reducer/movieReducer.js
Labels: fix

#194 fix: fix api
  src/Api/api.js
Labels: fix

#196 fix: movie page error
  src/Api/api.js
  src/Components/Molecules/RaderChartKeyPoint.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Reducer/movieReducer.js
Labels: fix

#199 feat : mypageApi
  src/Api/api.js
  src/Components/Molecules/MyMovieStoryComment.js
  src/Components/Molecules/MyMovieStoryFavorite.js
  src/Components/Molecules/MyMovieStoryWatched.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Components/Organisms/style/LoginForm.scss
  src/Components/Organisms/style/MainHeader.scss
  src/Components/Pages/MyPage.js
  src/Reducer/userInfoReducer.js
Labels: feature

#200 Fix: Resolved Error in sign up page and Connected id double check Api
  src/Api/api.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/SignUpForm.js
  src/Reducer/bookingReducer.js
  src/Reducer/bookingSeatReducer.js
Labels: fix

#202 feat: Auto scroll to timeline
  src/Components/Molecules/BookingSelectTime.js
  src/Components/Molecules/CarouselTimeline.js
  src/Reducer/bookingReducer.js
  src/Utils/util.js
Labels: feature

#206 Feat: Made Solved error when Making reservation #191
  src/Components/Molecules/BookingInfo.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Reducer/bookingReducer.js
  src/Reducer/bookingSeatReducer.js
Labels: feature

#207 fix: members api address
  src/Api/api.js
  src/Components/Organisms/NavSample.js
  src/Reducer/userInfoReducer.js
Labels: fix

#208 Fix: Modified double Popup and Feat: Added check Login feature when send reservation
  src/Components/Molecules/BookingPersonalCounter.js
  src/Components/Molecules/BookingSeatReset.js
Labels: fix

#210 feat: movieStory tab, userInfoReducer modify
  package-lock.json
  src/Components/Molecules/CarouselMovieStory.js
  src/Components/Molecules/MyMovieStoryTimeLine.js
  src/Components/Organisms/MyPage/MyMovieStory.js
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
  src/Components/Pages/MyPage.js
  src/Reducer/userInfoReducer.js
Labels: feature

#214 Fix: Reconnected make Reservation Api
  src/Api/api.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Reducer/bookingReducer.js
  src/Reducer/bookingSeatReducer.js
Labels: fix

#216 Feat: Made loading when select Seat and reset seat
  src/Components/Atoms/style/Loading.scss
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Reducer/bookingSeatReducer.js
Labels: feature

#217 fix: fix payment api
  package.json
  src/Api/api.js
  src/Components/Organisms/Booking/BookingPayment.js
  src/Components/Organisms/Booking/BookingTicket.js
  src/Components/Organisms/Booking/style/BookingTicket.scss
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Reducer/bookingReducer.js
  yarn.lock
Labels: fix

#218 feat: make search bar
  src/Api/api.js
  src/Components/Molecules/Search.js
  src/Components/Organisms/Main/MainBenefits.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/MainCuration.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Reducer/movieReducer.js
Labels: feature

#222 feat: make movie trailer page
  package-lock.json
  package.json
  src/Components/Organisms/MovieDetail/MovieDetailTab.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/MovieDetail/MovieTrailer.js
  src/Components/Organisms/MovieDetail/style/MovieDetailTab.scss
  src/Components/Organisms/MovieDetail/style/MovieTrailer.scss
  src/Components/Templates/MovieDetail.js
  yarn.lock
Labels: feature

#224 Feat: Made skeleton for loading MainMovies, Make Google sign-up and Style: Made animation in main Movie list
  src/Api/api.js
  src/Components/Atoms/SkeletonMainMovies.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/SignUpForm.js
  src/Reducer/bookingSeatReducer.js
Labels: feature

#227 feat: make skeleton in detail page and error in header
  src/Components/Atoms/SkeletonDetailPage.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/style/MainHeader.scss
  src/Reducer/movieReducer.js
Labels: feature

#229 feat: myMegabox
  package-lock.json
  src/Components/Molecules/MyMovieStoryComment.js
  src/Components/Molecules/MyMovieStoryFavorite.js
  src/Components/Molecules/MyMovieStoryTimeLine.js
  src/Components/Molecules/MyMovieStoryWatched.js
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/ConfirmPassword.js
  src/Components/Organisms/MyPage/EditOption.js
  src/Components/Organisms/MyPage/EditPassword.js
  src/Components/Organisms/MyPage/EditUserInfo.js
  src/Components/Organisms/MyPage/MyMovieStory.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Components/Organisms/MyPage/Snb.js
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
  src/Components/Pages/MyPage.js
  src/Components/Templates/MyMegaBox.js
  src/Reducer/userInfoReducer.js
  src/Utils/util.js
Labels: feature

#233 fix: fix time select bug
  src/Api/api.js
  src/Components/Molecules/BookingCancel.js
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingSelectTime.js
  src/Components/Molecules/style/BookingSelectTime.scss
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/style/LoginForm.scss
  src/Components/Pages/BookingPage.js
  src/Components/Pages/MainPage.js
  src/Components/Pages/MovieDetailPage.js
  src/Reducer/bookingReducer.js
  src/Utils/util.js
  src/setupProxy.js
Labels: fix

#235 Feat: Connected Google signup Api
  src/Api/api.js
  src/Components/Organisms/SignUpForm.js
  src/Components/Organisms/style/SignUpForm.scss
Labels: feature

#236 feat : mypageDashboard link
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MyPage/MyMovieStory.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Reducer/index.js
  src/Reducer/myMovieStoryReducer.js
  src/Reducer/userInfoReducerNewSample.js
Labels: feature

#237 feat: Make social login
  src/Api/api.js
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/SignUpForm.js
  src/Reducer/userInfoReducer.js
Labels: feature

#239 fix: fix mypage reloading bug
  src/Components/Pages/MyPage.js
  src/Reducer/userInfoReducer.js
Labels: fix

#241 fix: socialLogin api address
  src/Api/api.js
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Organisms/LoginForm.js
  src/Reducer/userInfoReducer.js
Labels: fix

#244 style: style modify
  public/favicon.ico
  src/Components/Atoms/style/BookingFastTitle.scss
  src/Components/Organisms/Booking/style/BookingPayment.scss
  src/Components/Organisms/Booking/style/BookingSelectMovie.scss
  src/Components/Organisms/Booking/style/BookingSelectSeat.scss
  src/Components/Organisms/Event/style/EventCommon.scss
  src/Components/Organisms/Footer.js
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/Main/style/MainLink.scss
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
  src/Components/Organisms/MyPage/style/Snb.scss
  src/Components/Organisms/SignUpForm.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Components/Organisms/style/Footer.scss
  src/Components/Organisms/style/LoginForm.scss
  src/Components/Organisms/style/MainHeader.scss
  src/Components/Organisms/style/SignUpForm.scss
  src/Components/Pages/style/mypage.scss
  src/common.scss
  src/images/favicon.png
  src/images/icon_closed.png
Labels: style

#243 Fix: Reconnect google sign up api
  src/Components/Organisms/SignUpForm.js
  src/Utils/theaterLocation.js
Labels: fix

#245 Feat: set theaterLocation
  src/Utils/theaterLocation.js
Labels: feature

#247 fix: fix mypage bug
  src/Api/api.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/MyMovieStory.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Reducer/bookingReducer.js
  src/Reducer/userInfoReducer.js
Labels: fix

#248 feat: subheader util hidden
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieTrailer.js
  src/Components/Organisms/MovieDetail/style/MovieTrailer.scss
  src/Components/Organisms/MyPage/Snb.js
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
  src/Components/Organisms/MyPage/style/MypageDashBoard.scss
  src/Components/Organisms/style/LoginForm.scss
  src/Components/Organisms/style/MainHeader.scss
Labels: feature

#250 fix: favorite page , theater location
  src/Api/api.js
  src/Components/Atoms/SkeletonWholeMoviePage.js
  src/Components/Molecules/LikeButtonModal.js
  src/Components/Molecules/MovieDetailComment.js
  src/Components/Molecules/MyMovieStoryFavorite.js
  src/Components/Molecules/Search.js
  src/Components/Molecules/style/MovieDetailComment.scss
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieDetailTab.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/style/MainHeader.scss
  src/Reducer/movieReducer.js
  src/Utils/theaterLocation.js
  src/common.scss
Labels: fix

#252 feat: Make cancel payment func
  src/Api/api.js
  src/Components/Molecules/BookingCancel.js
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Reducer/userInfoReducer.js
Labels: feature

#253 style: style Modify
  src/Components/Molecules/BookingTheaterList.js
  src/Components/Molecules/style/BookingTheaterList.scss
  src/Components/Organisms/Booking/BookingPayment.js
  src/Components/Organisms/Booking/style/BookingPayment.scss
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/MyMovieStory.js
  src/Components/Organisms/MyPage/MypageDashBoard.js
  src/Components/Organisms/MyPage/style/MypageDashBoard.scss
Labels: style

#255 Feat: Connected Login page when try Google login but not sign up
  src/Components/Molecules/PopupNotice.js
  src/Components/Organisms/SignUpForm.js
  src/Reducer/userInfoReducer.js
Labels: feature

#256 style: style modify & movie detail story open btn
  src/Components/Molecules/style/BookingPersonalSetting.scss
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/MovieDetail/style/MovieInforWrap.scss
  src/Components/Organisms/MyPage/MyMovieStory.js
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/common.scss
Labels: style

#257 fix: code
  src/Components/Atoms/SkeletonWholeMoviePage.js
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/LineDayAudience.js
  src/Components/Molecules/MyMovieStoryComment.js
  src/Components/Molecules/RaderChartKeyPoint.js
  src/Components/Organisms/Booking/BookingSelectSeat.js
  src/Components/Organisms/Event/RecommendEvent.js
  src/Components/Organisms/Footer.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/NavSample.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Reducer/bookingSeatReducer.js
  src/Reducer/movieReducer.js
  src/Reducer/userInfoReducer.js
Labels: fix

#258 Feat: Made Favorite feat
  src/Api/api.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Reducer/movieReducer.js
  src/Reducer/userInfoReducer.js
  src/common.scss
Labels: feature

#259 feat: create 404 nonFound Page
  src/Components/Molecules/MovieDetailComment.js
  src/Components/Organisms/MyPage/Snb.js
  src/Components/Organisms/MyPage/style/Snb.scss
  src/Components/Organisms/NotFound.js
  src/Components/Organisms/style/MainHeader.scss
  src/Components/Pages/NotFoundPage.js
  src/Components/Pages/style/notFound.scss
  src/Components/Templates/NotFoundWrap.js
  src/Reducer/myMovieStoryReducer.js
Labels: feature

#261 Fix: Solved Error when click favorite btn
  src/Components/Molecules/MyMovieStoryFavorite.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Reducer/userInfoReducer.js
Labels: fix

#262 fix: code
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Components/Organisms/style/MainHeader.scss
Labels: fix

#263 style: styleModify
  src/Components/Molecules/MyMovieStoryComment.js
  src/Components/Molecules/MyMovieStoryTimeLine.js
  src/Components/Molecules/MyMovieStoryWatched.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MyPage/BookingHistoryWrap.js
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
  src/Components/Organisms/style/MainHeader.scss
  src/Components/Pages/style/notFound.scss
Labels: style

#264 fix : css code
  src/Components/Molecules/MovieDetailComment.js
  src/Components/Organisms/Main/MainNotice.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
Labels: fix

#266 Fix: Some Errors
  src/Components/Molecules/PopupNotice.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Reducer/bookingReducer.js
  src/Reducer/movieReducer.js
Labels: fix

#267 fix: fix many bugs
  public/index.html
  src/Api/api.js
  src/Components/Atoms/CarouselNextArrow.js
  src/Components/Molecules/BookingCancel.js
  src/Components/Molecules/BookingInfo.js
  src/Components/Molecules/BookingMovieSchedules.js
  src/Components/Molecules/BookingSelectTime.js
  src/Components/Molecules/CarouselTimeline.js
  src/Components/Molecules/style/BookingMovieList.scss
  src/Components/Molecules/style/BookingMovieSchedules.scss
  src/Components/Molecules/style/BookingSelectTime.scss
  src/Components/Molecules/style/BookingTheaterList.scss
  src/Components/Molecules/style/CarouselCalendar.scss
  src/Components/Molecules/style/CarouselTimeline.scss
  src/Components/Organisms/Booking/BookingPayment.js
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/Main/MainNotice.js
  src/Components/Organisms/NavSample.js
  src/Components/Organisms/SignUpForm.js
  src/Components/Pages/EventPage.js
  src/Components/Pages/MovieDetailPage.js
  src/Components/Pages/WholeMovieListPage.js
  src/Components/Templates/Booking.js
  src/Components/Templates/Event.js
  src/Components/Templates/Main.js
  src/Components/Templates/MyMegaBox.js
  src/Components/Templates/WholeMovieList.js
  src/Reducer/bookingReducer.js
  src/Reducer/userInfoReducer.js
  src/Utils/payment.js
  src/Utils/theaterLocation.js
  src/Utils/util.js
  src/common.scss
  src/index.js
Labels: fix

#269 Docs: Added content README.md
  README.md
Labels: docs

#270 delete: delete console log
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Reducer/movieReducer.js
Labels: fix

#271 fix: change logo
  public/logo192.png
  public/logo512.png
Labels: fix

#274 style: main page style modify
  src/Components/Organisms/Main/style/MainCuration.scss
  src/Components/Organisms/Main/style/MainNotice.scss
  src/Components/Organisms/Main/style/MainTheater.scss
Labels: style

#275 fix some style
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
Labels: fix

#276 fix: main page scss code
  src/App.js
  src/Components/Organisms/Footer.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/MainCuration.js
  src/Components/Organisms/Main/MainLink.js
  src/Components/Organisms/Main/style/MainCuration.scss
  src/Components/Organisms/Main/style/MainLink.scss
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/style/MainHeader.scss
  src/Reducer/movieReducer.js
  src/app.scss
Labels: fix

#277 Revert "fix: main page scss code"
  src/App.js
  src/Components/Organisms/Footer.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/MainCuration.js
  src/Components/Organisms/Main/MainLink.js
  src/Components/Organisms/Main/style/MainCuration.scss
  src/Components/Organisms/Main/style/MainLink.scss
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/style/MainHeader.scss
  src/Reducer/movieReducer.js
  src/app.scss
Labels: fix

#279 fix: fix infinity gps request
  src/Components/Molecules/BookingTheaterList.js
  src/Utils/theaterLocation.js
Labels: fix

#280 fix: fix styles
  public/index.html
  src/Components/Organisms/Footer.js
  src/Components/Organisms/Header.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/Main/MainCuration.js
  src/Components/Organisms/Main/MainTheater.js
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Components/Pages/BookingPage.js
  src/Components/Pages/EventPage.js
  src/Components/Pages/MyPage.js
  src/Components/Pages/style/mypage.scss
  src/Components/Templates/Main.js
  src/Reducer/movieReducer.js
Labels: fix

#283 fix: fix button style
  src/Components/Organisms/Main/style/MainBoxOffice.scss
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
Labels: fix, style

#284 font import modify
  src/common.scss
Labels: fix

#285 fix: fix some styles
  src/Components/Molecules/MovieDetailComment.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MovieDetail/MovieDetailTab.js
  src/Components/Organisms/MovieDetail/MovieDetailWrap.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
Labels: fix, style

#286 fix: remove uesless things
  public/index.html
  src/App.js
  src/Components/Organisms/MovieDetail/MovieInforWrap.js
  src/Components/Organisms/MovieDetail/MovieTrailer.js
  src/Components/Pages/EventPage.js
Labels: fix

#287 style: listNull style modify
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
Labels: fix, style

#288 docs: fix Readme
  README.md
Labels: docs, fix

#289 feat: Make theater info page
  README.md
  src/Components/Organisms/MainHeader.js
  src/Components/Pages/TheaterInfoPage.js
  src/Components/Templates/TheaterInfo.js
  src/Components/Templates/style/TheaterInfo.scss
  src/Router/MainRouter.js
Labels: feature, style

#291 feat: Make TheaterInfo page
  src/Components/Atoms/BookingFastTitle.js
  src/Components/Atoms/TheaterInfoTitle.js
  src/Components/Atoms/style/TheaterInfoTitle.scss
  src/Components/Molecules/TeatherMap.js
  src/Components/Molecules/TheaterInfoSelect.js
  src/Components/Molecules/style/BookingTheaterList.scss
  src/Components/Molecules/style/TheaterMap.scss
  src/Components/Templates/TheaterInfo.js
  src/Components/Templates/style/TheaterInfo.scss
  src/Reducer/index.js
  src/Reducer/theaterInfoReducer.js
  src/Router/SubBookingRouter.js
Labels: feature

#290 style: mymoviestory date
  src/Components/Molecules/MyMovieStoryTimeLine.js
  src/Components/Organisms/MyPage/style/MyMovieStory.scss
Labels: style

#292 feat: Make lazy loading
  src/Components/Molecules/BookingCancel.js
  src/Components/Organisms/Main/MainBoxOffice.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/WholeMovieList/WholeMovieListWrap.js
  src/Components/Organisms/WholeMovieList/style/WholeMovieListWrap.scss
  src/Reducer/userInfoReducer.js
  src/Utils/theaterLocation.js
Labels: feature

#295 fix: fix login check bug
  src/Api/api.js
  src/Components/Pages/BookingPage.js
  src/Components/Pages/MyPage.js
  src/Components/Templates/Booking.js
  src/Components/Templates/MyMegaBox.js
Labels: fix

#298 docs: Write bugfix history
  README.md
Labels: docs

#297 Fix: Refactory PopupNotice
  src/App.js
  src/Components/Molecules/BookingCancel.js
  src/Components/Molecules/BookingPersonalCounter.js
  src/Components/Molecules/BookingSeatList.js
  src/Components/Molecules/BookingSeatReset.js
  src/Components/Molecules/PopupNotice.js
  src/Components/Molecules/ticketVoucher.js
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/MainHeader.js
  src/Components/Organisms/ModalForm.js
  src/Components/Organisms/SignUpForm.js
  src/Components/Templates/Booking.js
  src/Components/Templates/MyMegaBox.js
  src/Reducer/index.js
  src/Reducer/modalReducer.js
  src/Utils/bookingSeatUtils.js
Labels: fix

#300 fix: mypage & booking page bugs
  src/Api/api.js
  src/Components/Molecules/MyMovieStoryTimeLine.js
  src/Components/Molecules/TheaterInfoSelect.js
  src/Components/Molecules/style/BookingPersonalSetting.scss
  src/Components/Organisms/LoginForm.js
  src/Components/Organisms/Main/MainLink.js
  src/Components/Organisms/Main/style/MainLink.scss
  src/Components/Organisms/NavSample.js
  src/Reducer/bookingReducer.js
  src/Reducer/userInfoReducer.js
Labels: fix
